### ISSUE TITLE
Release for Flashing SD card possible

### ISSUE THREAD

**Issue by PlumbumDN** [InfoteamEnergySolutions/openwrt#1]
Hi,
it is not a real issue, but how to flash OpenLorix onto an mSD card and not FLASH the original firmware in NAND?
Best regards,
Robert

**Comment by TMesot** [comment]
Hello, 

We do not plan to support SD card, as you can still flash back the LORIXOne official firmware after having flashed OpenLORIX.

Here is the procedure and the last official firmware : https://www.lorixone.io/wiki/Programming_Tool

If you want to try by yourself, it doesn't seems a lot of job as : 

- By default, LORIXOne seems to always try to boot from SD and if not found, it switch to internal memory.
- LORIXOne firmware is available as SDCard firmware, so you can inspire yourself

You will need to : 

- Create a SD card with partition layout as boot partition in FAT16, with boot flag and second one in ext4 with rootfs
- Fix file naming and maybe change bootloader configuration to load file and not memory addresses
- Maybe fix the firmware upgrade mechanism in OpenLORIX. 

Hope it helps, 
Titouan
